// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TayFinitiv.Database;

namespace TayFinitiv.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210114003435_AddEverythingBack")]
    partial class AddEverythingBack
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TayFinitiv.Shared.TellerMachine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Fifties")
                        .HasColumnType("int");

                    b.Property<int>("Fives")
                        .HasColumnType("int");

                    b.Property<int>("Hundreds")
                        .HasColumnType("int");

                    b.Property<int>("Ones")
                        .HasColumnType("int");

                    b.Property<int>("Tens")
                        .HasColumnType("int");

                    b.Property<int>("Twenties")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ATMs");
                });

            modelBuilder.Entity("TayFinitiv.Shared.WithdrawRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AmountRequested")
                        .HasColumnType("int");

                    b.Property<int>("DenominationRequested")
                        .HasColumnType("int");

                    b.Property<string>("MessageToUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RequestInstant")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
